function TT = calcConvertedSignals(TT, x)
%CALCCONVERTEDSIGNALS Summary of this function goes here
%   Detailed explanation goes here
arguments
    TT timetable
    x.deleteOldName logical = false
    x.signalNotFound string = "error"
end

translations_and_conversions = ...
    {'RootMyc1', 'FlappingMoment1_MNm', 1e-3; ...
    'RootMyc2', 'FlappingMoment2_MNm', 1e-3; ...
    'RootMyc3', 'FlappingMoment3_MNm', 1e-3; ...
    'BldPitch1', 'BldPitch1_deg', 1; ...
    'BldPitch2', 'BldPitch2_deg', 1; ...
    'BldPitch3', 'BldPitch3_deg', 1; ...
    'RtSpeed', 'RtSpeed_rpm', 1; ...
    'GenTq', 'GenTq_MNm', 1e-3; ...
    'GenPwr', 'GenPwr_MW', 1e-3; ...
    'TipDyc1', 'TipDyc1_m', 1; ...
    'theta_0', 'theta_0_deg', rad2deg(1); ...
    'theta_tilt', 'theta_tilt_deg', rad2deg(1); ...
    'theta_yaw', 'theta_yaw_deg', rad2deg(1); ...
    'theta_1', 'theta_1_deg', rad2deg(1); ...
    'theta_2', 'theta_2_deg', rad2deg(1); ...
    'theta_3', 'theta_3_deg', rad2deg(1); ...
    'theta_phi', 'theta_phi_deg', rad2deg(1); ...
    'theta_r', 'theta_r_deg', rad2deg(1); ...
    'theta_CPC', 'theta_CPC_deg', rad2deg(1); ...
    'M_0', 'M_0_MNm', 1e-3; ...
    'M_tilt', 'M_tilt_MNm', 1e-3; ...
    'M_yaw', 'M_yaw_MNm', 1e-3; ...
    'M_tilt_0', 'M_tilt_0_MNm', 1e-3; ...
    'M_yaw_0', 'M_yaw_0_MNm', 1e-3; ...
    'M_r', 'M_r_MNm', 1e-3; ...
    'M_phi', 'M_phi_MNm', 1e-3; ...
    };

[N, ~] = size(translations_and_conversions);
for i = 1:N
    oldname = translations_and_conversions{i, 1};
    newname = translations_and_conversions{i, 2};
    conversion = translations_and_conversions{i, 3};
    
    if ismember(oldname, fieldnames(TT))
        TT.(newname) = TT.(oldname) * conversion;
        if x.deleteOldName
            TT = removevars(TT, oldname);
        end
    else
        switch x.signalNotFound
            case "none"
                continue
            case "warning"
                warning("Couldn't find signal %s in timetable.", oldname);
                continue
            otherwise
                error("Couldn't find signal %s in timetable.", oldname);
        end
    end
end

end
